spring:
  application:
    name: lovableclone
    description: this is application

  datasource:
    url: jdbc:postgresql://localhost:5432/testdb
    username: postgres
    password: Manish@123
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true